// src/components/features/auth/countries.ts
// داده‌های کشورها و کد تماس برای ورود با شماره تلفن مشتریان

export interface Country {
  code: string;
  nameFa: string;
  nameEn: string;
  dialCode: string;
}

export const flagUrl = (code: string) =>
  `https://flagcdn.com/w40/${code.toLowerCase()}.png`;

export const DEFAULT_COUNTRY: Country = {
  code: 'IR',
  nameFa: 'ایران',
  nameEn: 'Iran',
  dialCode: '+98',
};

export const COUNTRIES: Country[] = [
  DEFAULT_COUNTRY,
  { code: 'US', nameFa: 'ایالات متحده', nameEn: 'United States', dialCode: '+1' },
  { code: 'GB', nameFa: 'بریتانیا', nameEn: 'United Kingdom', dialCode: '+44' },
  { code: 'CA', nameFa: 'کانادا', nameEn: 'Canada', dialCode: '+1' },
  { code: 'AU', nameFa: 'استرالیا', nameEn: 'Australia', dialCode: '+61' },
  { code: 'DE', nameFa: 'آلمان', nameEn: 'Germany', dialCode: '+49' },
  { code: 'FR', nameFa: 'فرانسه', nameEn: 'France', dialCode: '+33' },
  { code: 'AE', nameFa: 'امارات متحده عربی', nameEn: 'United Arab Emirates', dialCode: '+971' },
  { code: 'SA', nameFa: 'عربستان سعودی', nameEn: 'Saudi Arabia', dialCode: '+966' },
  { code: 'TR', nameFa: 'ترکیه', nameEn: 'Turkey', dialCode: '+90' },
  { code: 'PK', nameFa: 'پاکستان', nameEn: 'Pakistan', dialCode: '+92' },
  { code: 'IN', nameFa: 'هند', nameEn: 'India', dialCode: '+91' },
  { code: 'CN', nameFa: 'چین', nameEn: 'China', dialCode: '+86' },
  { code: 'JP', nameFa: 'ژاپن', nameEn: 'Japan', dialCode: '+81' },
  { code: 'KR', nameFa: 'کره جنوبی', nameEn: 'South Korea', dialCode: '+82' },
  { code: 'RU', nameFa: 'روسیه', nameEn: 'Russia', dialCode: '+7' },
  { code: 'ES', nameFa: 'اسپانیا', nameEn: 'Spain', dialCode: '+34' },
  { code: 'IT', nameFa: 'ایتالیا', nameEn: 'Italy', dialCode: '+39' },
  { code: 'NL', nameFa: 'هلند', nameEn: 'Netherlands', dialCode: '+31' },
  { code: 'SE', nameFa: 'سوئد', nameEn: 'Sweden', dialCode: '+46' },
  { code: 'NO', nameFa: 'نروژ', nameEn: 'Norway', dialCode: '+47' },
  { code: 'DK', nameFa: 'دانمارک', nameEn: 'Denmark', dialCode: '+45' },
  { code: 'FI', nameFa: 'فنلاند', nameEn: 'Finland', dialCode: '+358' },
  { code: 'CH', nameFa: 'سوئیس', nameEn: 'Switzerland', dialCode: '+41' },
  { code: 'AT', nameFa: 'اتریش', nameEn: 'Austria', dialCode: '+43' },
  { code: 'BE', nameFa: 'بلژیک', nameEn: 'Belgium', dialCode: '+32' },
  { code: 'IE', nameFa: 'ایرلند', nameEn: 'Ireland', dialCode: '+353' },
  { code: 'PT', nameFa: 'پرتغال', nameEn: 'Portugal', dialCode: '+351' },
  { code: 'BR', nameFa: 'برزیل', nameEn: 'Brazil', dialCode: '+55' },
  { code: 'MX', nameFa: 'مکزیک', nameEn: 'Mexico', dialCode: '+52' },
  { code: 'AR', nameFa: 'آرژانتین', nameEn: 'Argentina', dialCode: '+54' },
  { code: 'CO', nameFa: 'کلمبیا', nameEn: 'Colombia', dialCode: '+57' },
  { code: 'CL', nameFa: 'شیلی', nameEn: 'Chile', dialCode: '+56' },
  { code: 'PE', nameFa: 'پرو', nameEn: 'Peru', dialCode: '+51' },
  { code: 'EG', nameFa: 'مصر', nameEn: 'Egypt', dialCode: '+20' },
  { code: 'MA', nameFa: 'مراکش', nameEn: 'Morocco', dialCode: '+212' },
  { code: 'TN', nameFa: 'تونس', nameEn: 'Tunisia', dialCode: '+216' },
  { code: 'DZ', nameFa: 'الجزایر', nameEn: 'Algeria', dialCode: '+213' },
  { code: 'JO', nameFa: 'اردن', nameEn: 'Jordan', dialCode: '+962' },
  { code: 'KW', nameFa: 'کویت', nameEn: 'Kuwait', dialCode: '+965' },
  { code: 'QA', nameFa: 'قطر', nameEn: 'Qatar', dialCode: '+974' },
  { code: 'BH', nameFa: 'بحرین', nameEn: 'Bahrain', dialCode: '+973' },
  { code: 'OM', nameFa: 'عمان', nameEn: 'Oman', dialCode: '+968' },
  { code: 'IQ', nameFa: 'عراق', nameEn: 'Iraq', dialCode: '+964' },
  { code: 'LB', nameFa: 'لبنان', nameEn: 'Lebanon', dialCode: '+961' },
  { code: 'SY', nameFa: 'سوریه', nameEn: 'Syria', dialCode: '+963' },
  { code: 'AZ', nameFa: 'جمهوری آذربایجان', nameEn: 'Azerbaijan', dialCode: '+994' },
  { code: 'AM', nameFa: 'ارمنستان', nameEn: 'Armenia', dialCode: '+374' },
  { code: 'GE', nameFa: 'گرجستان', nameEn: 'Georgia', dialCode: '+995' },
  { code: 'KZ', nameFa: 'قزاقستان', nameEn: 'Kazakhstan', dialCode: '+7' },
  { code: 'UZ', nameFa: 'ازبکستان', nameEn: 'Uzbekistan', dialCode: '+998' },
  { code: 'TM', nameFa: 'ترکمنستان', nameEn: 'Turkmenistan', dialCode: '+993' },
  { code: 'KG', nameFa: 'قرقیزستان', nameEn: 'Kyrgyzstan', dialCode: '+996' },
  { code: 'TJ', nameFa: 'تاجیکستان', nameEn: 'Tajikistan', dialCode: '+992' },
  { code: 'AF', nameFa: 'افغانستان', nameEn: 'Afghanistan', dialCode: '+93' },
  { code: 'ID', nameFa: 'اندونزی', nameEn: 'Indonesia', dialCode: '+62' },
  { code: 'MY', nameFa: 'مالزی', nameEn: 'Malaysia', dialCode: '+60' },
  { code: 'SG', nameFa: 'سنگاپور', nameEn: 'Singapore', dialCode: '+65' },
  { code: 'TH', nameFa: 'تایلند', nameEn: 'Thailand', dialCode: '+66' },
  { code: 'VN', nameFa: 'ویتنام', nameEn: 'Vietnam', dialCode: '+84' },
  { code: 'PH', nameFa: 'فیلیپین', nameEn: 'Philippines', dialCode: '+63' },
  { code: 'HK', nameFa: 'هنگ‌کنگ', nameEn: 'Hong Kong', dialCode: '+852' },
  { code: 'TW', nameFa: 'تایوان', nameEn: 'Taiwan', dialCode: '+886' },
  { code: 'NZ', nameFa: 'نیوزیلند', nameEn: 'New Zealand', dialCode: '+64' },
  { code: 'ZA', nameFa: 'آفریقای جنوبی', nameEn: 'South Africa', dialCode: '+27' },
  { code: 'NG', nameFa: 'نیجریه', nameEn: 'Nigeria', dialCode: '+234' },
  { code: 'KE', nameFa: 'کنیا', nameEn: 'Kenya', dialCode: '+254' },
  { code: 'ET', nameFa: 'اتیوپی', nameEn: 'Ethiopia', dialCode: '+251' },
  { code: 'GH', nameFa: 'غنا', nameEn: 'Ghana', dialCode: '+233' },
  { code: 'TZ', nameFa: 'تانزانیا', nameEn: 'Tanzania', dialCode: '+255' },
  { code: 'UA', nameFa: 'اوکراین', nameEn: 'Ukraine', dialCode: '+380' },
  { code: 'BY', nameFa: 'بلاروس', nameEn: 'Belarus', dialCode: '+375' },
  { code: 'PL', nameFa: 'لهستان', nameEn: 'Poland', dialCode: '+48' },
  { code: 'CZ', nameFa: 'جمهوری چک', nameEn: 'Czech Republic', dialCode: '+420' },
  { code: 'SK', nameFa: 'اسلواکی', nameEn: 'Slovakia', dialCode: '+421' },
  { code: 'HU', nameFa: 'مجارستان', nameEn: 'Hungary', dialCode: '+36' },
  { code: 'RO', nameFa: 'رومانی', nameEn: 'Romania', dialCode: '+40' },
  { code: 'BG', nameFa: 'بلغارستان', nameEn: 'Bulgaria', dialCode: '+359' },
  { code: 'GR', nameFa: 'یونان', nameEn: 'Greece', dialCode: '+30' },
  { code: 'HR', nameFa: 'کرواسی', nameEn: 'Croatia', dialCode: '+385' },
  { code: 'RS', nameFa: 'صربستان', nameEn: 'Serbia', dialCode: '+381' },
  { code: 'BA', nameFa: 'بوسنی و هرزگوین', nameEn: 'Bosnia and Herzegovina', dialCode: '+387' },
  { code: 'SI', nameFa: 'اسلوونی', nameEn: 'Slovenia', dialCode: '+386' },
  { code: 'IL', nameFa: 'اسرائیل', nameEn: 'Israel', dialCode: '+972' },
  { code: 'CY', nameFa: 'قبرس', nameEn: 'Cyprus', dialCode: '+357' },
  { code: 'MT', nameFa: 'مالت', nameEn: 'Malta', dialCode: '+356' },
  { code: 'IS', nameFa: 'ایسلند', nameEn: 'Iceland', dialCode: '+354' },
  { code: 'LU', nameFa: 'لوکزامبورگ', nameEn: 'Luxembourg', dialCode: '+352' },
  { code: 'MC', nameFa: 'موناکو', nameEn: 'Monaco', dialCode: '+377' },
  { code: 'LI', nameFa: 'لیختن‌اشتاین', nameEn: 'Liechtenstein', dialCode: '+423' },
  { code: 'AD', nameFa: 'آندورا', nameEn: 'Andorra', dialCode: '+376' },
  { code: 'SM', nameFa: 'سان مارینو', nameEn: 'San Marino', dialCode: '+378' },
  { code: 'VA', nameFa: 'واتیکان', nameEn: 'Vatican City', dialCode: '+379' },
  { code: 'AL', nameFa: 'آلبانی', nameEn: 'Albania', dialCode: '+355' },
  { code: 'MK', nameFa: 'مقدونیه شمالی', nameEn: 'North Macedonia', dialCode: '+389' },
  { code: 'ME', nameFa: 'مونته‌نگرو', nameEn: 'Montenegro', dialCode: '+382' },
  { code: 'PS', nameFa: 'فلسطین', nameEn: 'Palestine', dialCode: '+970' },
  { code: 'YE', nameFa: 'یمن', nameEn: 'Yemen', dialCode: '+967' },
  { code: 'SD', nameFa: 'سودان', nameEn: 'Sudan', dialCode: '+249' },
  { code: 'LY', nameFa: 'لیبی', nameEn: 'Libya', dialCode: '+218' },
];
